GET http://localhost:3000/
###
GET http://localhost:3000/api/customer
###
GET http://localhost:3000/api/customer/65ac875091ff65c7edf2e306
###
POST http://localhost:3000/api/customer HTTP/1.1
Content-Type: application/json

{
    "CustomerId": 1004,
    "FullName": "เจนจิรา สุขใจจริง",
    "Address": "สมุทรสงคราม"
}
###
POST http://localhost:3000/api/customer HTTP/1.1
Content-Type: application/json

{
    "CustomerId": 1005,
    "FullName": "พงศธรณ์ นาคเรือง",
    "Address": "สมุทรปราการ"
}
###
PUT http://localhost:3000/api/customer/65ac875091ff65c7edf2e306 HTTP/1.1
Content-Type: application/json

{
    "CustomerId": 1004,
    "FullName": "ศักดิ์ชัย มิตรกิจเจริญ",
    "Address": "USA"
}
###
DELETE http://localhost:3000/api/customer/65ac875091ff65c7edf2e306 HTTP/1.1